/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 6.0_1 */
public interface CalculatorTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTEXPRESSION = 2;
  public int JJTADD = 3;
  public int JJTSUB = 4;
  public int JJTMUL = 5;
  public int JJTDIV = 6;
  public int JJTINTEGER = 7;
  public int JJTSYMBOL = 8;
  public int JJTASSIGNMENT = 9;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Expression",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Integer",
    "Symbol",
    "Assignment",
  };
}
/* JavaCC - OriginalChecksum=3f3c93c6f0981c761b41c55df7b88879 (do not edit this line) */
