import java.util.Set;

/* Generated By:JJTree: Do not edit this line. ASTNumeric.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTNumeric extends SimpleNode {
    public ASTNumeric(int id) {
        super(id);
        this.returnType = "int";
    }

    public ASTNumeric(Parser p, int id) {
        super(p, id);
        this.returnType = "int";
    }

    @Override
    public String analyze(Descriptor descriptor, Set<String> variables){
        return this.returnType;
    }

    @Override
    public void generateCode(Descriptor descriptor){
        parser.addInstruction(JVMHelper.loadNumber(Integer.parseInt((String)this.jjtGetValue())));
    }

}
/*
 * JavaCC - OriginalChecksum=d1df27becc141526f727d9a5e4174f25 (do not edit this
 * line)
 */
