import exceptions.SemanticParseException;
import java.util.Set;

/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTProgram extends SimpleNode {
    public ASTProgram(int id) {
        super(id);
    }

    public ASTProgram(Parser p, int id) {
        super(p, id);
    }

    @Override
    public String analyze(Descriptor descriptor, Set<String> variables) throws SemanticParseException {
        for (int i = 0; i < this.jjtGetNumChildren(); i++)
            try {

                this.jjtGetChild(i).analyze(descriptor, variables);
            } catch (SemanticParseException ex) {

            }
        return "";
    }

    public void generateCode(Descriptor descriptor) {

        this.parser.addInstruction(new JVMInstruction(".source " + this.parser.fileName,0));

        for (int i = 0; i < this.jjtGetNumChildren(); i++)
                this.jjtGetChild(i).generateCode(descriptor);

        return;
    };

}
/*
 * JavaCC - OriginalChecksum=94c2c5e1c9ec2939f839804a5dc310ba (do not edit this
 * line)
 */
