import exceptions.SemanticParseException;
import java.util.Set;

/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTReturn extends SimpleNode {
    public ASTReturn(int id) {
        super(id);
    }

    public ASTReturn(Parser p, int id) {
        super(p, id);
    }
    @Override
    public String analyze(Descriptor descriptor, Set<String> variables) throws SemanticParseException{

        try{

            return this.jjtGetChild(0).analyze((MethodDescriptor) descriptor, variables);
        }
        catch(SemanticParseException ex){
            
        }

        return "";
    }

    @Override
    public void generateCode(Descriptor descriptor){

        this.jjtGetChild(0).generateCode(descriptor);
    }

}
/*
 * JavaCC - OriginalChecksum=0d7badc8de429fd7f39c8b2723d9a136 (do not edit this
 * line)
 */
