import java.util.Set;

/* Generated By:JJTree: Do not edit this line. ASTType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTType extends SimpleNode {
    public ASTType(int id) {
        super(id);
    }

    public ASTType(Parser p, int id) {
        super(p, id);
    }

    @Override
    public String analyze(Descriptor descriptor, Set<String> variables) {
        this.returnType = (String) this.jjtGetValue();
        return this.returnType;
    }

}
/*
 * JavaCC - OriginalChecksum=4802d77cbd42a285c599e5af18a60848 (do not edit this
 * line)
 */
